development:
  adapter: mysql2
  host: 0.0.0.0
  encoding: utf8mb4
  reconnect: true
  database: hablameapp
  pool: 5
  username: root
  password: wO^g8J!9yHNg
test:
  adapter: mysql2
  encoding: utf8mb4
  host: 0.0.0.0
  reconnect: true
  database: hablameapp
  pool: 5
  username: root
  password: wO^g8J!9yHNg
production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  host: 0.0.0.0
  database: hablameappproduction
  pool: 5
  username: root
  password: wO^g8J!9yHNg
