development:
  adapter: mysql2
  host: mariadbtest2
  encoding: utf8mb4
  reconnect: true
  database: hablameapp
  pool: 5
  username: root
  password: Honduras2016FTW
test:
  adapter: mysql2
  encoding: utf8mb4
  host: mariadbtest2
  reconnect: true
  database: hablameapp
  pool: 5
  username: root
  password: Honduras2016FTW
production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  host: mariadbtest2
  database: hablameappproduction
  pool: 5
  username: root
  password: Honduras2016FTW
